### ISSUE TITLE
DND5e сделать опцию: расположить скилы на чарнике в алфовитном порядке

### ISSUE THREAD

**Issue by BlackburnUTG** [Phenomen/foundry-vtt-ru#1]
в английской версии все скилы расположены в алфавитном порядке, при переводе расположение скилов сохранилось, но теперь они расположены не в алфавитном порядке, из-за чего найти нужный скилл в чарлисте бывает не просто.
можно ли сделать опцию, которая бы расположила скилы по алфавиту?
или если нельзя: может лучше задать принудительно?

**Comment by Phenomen** [comment]
Alphabetical sorting is added in #400fc76eba7bf374b4410ba4733d8e1664263d63
