### ISSUE TITLE
SW Rpg - предложение по изменению перевода - commited

### ISSUE THREAD

**Issue by BlackburnUTG** [Phenomen/foundry-vtt-ru#10]
Предлагаю поменять перевод слова commited c "использованы" на "отложены" . Я как раз доделываю перевод Phantom Studio ЗВ РПГ, и у них уже была переведена глава книги правил про силу.  Phantom studio переводили commit force die, как - отложить кубик Силы, т..к смысл механики в том что у тебя есть пул кубиков Силы который ты используешь как для проверок использования силы, так и для активации продолжительных эффектов путём убирания-откладывания кубиков из пула. И эти кубики можно вернуть обратно в пул в любой момент, прекратив использование продолжительного эффекта
..
ну и "использован" - не помещается в отведенное окошечко, а "отложены" - помещается 
![изображение](https://user-images.githubusercontent.com/19798113/124824921-4235fe80-df73-11eb-9d9d-861b8898e31e.png) 
![изображение](https://user-images.githubusercontent.com/19798113/124825151-8e813e80-df73-11eb-9291-fb8aa6b9fd3c.png)

**Comment by Phenomen** [comment]
Готово.
