### ISSUE TITLE
кнопка "Edit world" переведена как "Настройки"

### ISSUE THREAD

**Issue by BlackburnUTG** [Phenomen/foundry-vtt-ru#11]
настройки мира мейби?
![изображение](https://user-images.githubusercontent.com/19798113/125211047-d2da4a80-e2a3-11eb-936c-fa614080978c.png)
![изображение](https://user-images.githubusercontent.com/19798113/125211050-da99ef00-e2a3-11eb-8973-c0af54d51e8a.png)

**Comment by Phenomen** [comment]
Fixed in #55a564061941638dabb2bc6b53481237e1f6eac6
