### ISSUE TITLE
SW Rpg не переведен текст в чате при переворачивании жетонов Судьбы

### ISSUE THREAD

**Issue by BlackburnUTG** [Phenomen/foundry-vtt-ru#12]
![Снимок](https://user-images.githubusercontent.com/19798113/125702395-7464ba71-cb18-488c-83b4-2f2c0d18a8c7.PNG)

**Comment by Phenomen** [comment]
Please ask the system developer to add localization support to the following file: **starwarsffg\modules\ffg-destiny-tracker.js**

**Comment by BlackburnUTG** [comment]
они спрашивают меня, " Do you have your own localization file that could be added to the system?"
https://github.com/StarWarsFoundryVTT/StarWarsFFG/issues/953
