### ISSUE TITLE
Sw rpg - перевод навыков знания

### ISSUE THREAD

**Issue by BlackburnUTG** [Phenomen/foundry-vtt-ru#13]
Core Worlds - не "основные миры", а "Миры Ядра"
Underworld  - не "преисподняя", а "Преступный Мир" 
![изображение](https://user-images.githubusercontent.com/19798113/126064592-35f03742-a890-4b08-9643-a5830630dfe7.png)

**Comment by Phenomen** [comment]
Изменил Core Worlds на Центральный Миры
https://starwars.fandom.com/ru/wiki/Центральные_Миры/Канон

Исправил Преступный мир
