### ISSUE TITLE
Не видно CR

### ISSUE THREAD

**Issue by Astamariymelrock** [Phenomen/foundry-vtt-ru#14]
цифра показателя опасности находится вне поля листа персонажа

**Comment by Phenomen** [comment]
@Astamariymelrock модуль перевода включён в текущем мире? (не выбор языка, а именно модуль в списке)

**Comment by Astamariymelrock** [comment]
Да. Модуль перевода на русский язык влючен.Отправлено с устройства Galaxy

**Comment by Astamariymelrock** [comment]
Да. Включен. Когда выключен cr виденОтправлено с устройства Galaxy

**Comment by Astamariymelrock** [comment]
эта проблема только у меня наблюдается?

**Comment by Phenomen** [comment]
Ошибка исправлена.
