### ISSUE TITLE
Проблема со StarFinder

### ISSUE THREAD

**Issue by Zendelll** [Phenomen/foundry-vtt-ru#18]
Если включен русский перевод фаундри, то в старфайндере при попытке открыть любой лист, в консоли появляется ошибка "An error occurred while rendering ActorSheetSFRPGCharacter 48: Cannot read property 'max' of undefined", а лист просто не открывается
![image](https://user-images.githubusercontent.com/36535126/132912297-3b4549f6-1bd3-4a60-8eab-ad50ebc8aa92.png)
Из-за этого невозможно играть в эту систему с русским переводом.
Версия фаундри — 0.8.9
Версия аддона — 0.9.2.9
Выглядит, как довольно критическая штука, честно говоря

**Comment by Phenomen** [comment]
Исправлено
