### ISSUE TITLE
Отсутствует создание NPC

### ISSUE THREAD

**Issue by Nemo-Illusionist** [Phenomen/foundry-vtt-ru#2]
При создании актёра:
- ENG: "Non-Player Character" создаёт "Default 5e NPC Sheet"
- RU: "Персонаж ведущего" создаёт "Стандартный бланк персонажа 5e" что соответствует в английской версии "Default 5e Character Sheet"

**Comment by Phenomen** [comment]
Не могу воспроизвести ваш репорт. Опции "Персонаж игрока" и "Персонаж ведущего" создают соответствующие листы (PC/NPC). Проверил со стандартными листами и с Tidy5e.
