### ISSUE TITLE
В системе Savage Worlds не открывается лист персонажа игрока

### ISSUE THREAD

**Issue by Tipakot** [phenomen/foundry-vtt-ru#38]
При установленном модуле перевода, в системе Savage Worlds невозможно открыть лист персонажа игрока.

**Comment by Phenomen** [comment]
Версии системы SWADE, модуля перевода и Foundry?

**Comment by Tipakot** [comment]
Foundry - 9.249
SWADE - 1.0.3
Перевод - 0.9.4.81

**Comment by Phenomen** [comment]
Обновил строки под последнюю версии системы (пока не перевёл их). Проверил, бланки открываются. Обнови модуль перевода.

**Comment by Tipakot** [comment]
Работает. Спасибо.
