### ISSUE TITLE
В системе pathfinder 2e не открываются листы персонажей

### ISSUE THREAD

**Issue by Zendelll** [phenomen/foundry-vtt-ru#39]
При попытке открыть лист с установленным русским языком вижу вот такое (скрин). Также пропали все компендиумы. Если сменить язык в настройках на английский, все становится нормально
![image](https://user-images.githubusercontent.com/36535126/161322181-c183d8a1-f68f-4415-bfa7-f25b65d70499.png)
Версия модуля — 0.9.4.97
Версия системы — 3.7.2.10819
Версия фаундри — 9, сборка 255

**Comment by phenomen** [comment]
Перевод удалён до лучших времён.

**Comment by Zendelll** [comment]
Больно :с
Надеюсь, получится вскоре вернуть(

**Comment by phenomen** [comment]
К сожалению, Hobby World так и не выпустили даже Gamemaster's Guide и Bestiary. Я уж молчу о десятке последующих дополнений. Поэтому обновление не представляется возможным.

**Comment by Zendelll** [comment]
Да, это очень грустно, конечно( Но в любом случае спасибо! Теперь хотя бы работает без смены языка)
