### ISSUE TITLE
Feature Request - Genesys/Star Wars - RUS

### ISSUE THREAD

**Issue by BlackburnUTG** [Phenomen/foundry-vtt-ru#4]
На днях вышла официальная русская локализация для Генезис. 
https://hobbygames.ru/genesys-osnovnaja-kniga-pravil?utm_source=hw&utm_medium=cpc&utm_campaign=buy_button

Было бы здорово если бы появился перевод системы в фаундри 
https://github.com/StarWarsFoundryVTT/StarWarsFFG

**Comment by Phenomen** [comment]
Было бы здорово, но книги в электронном виде у меня нет.

**Comment by BlackburnUTG** [comment]
на
https://drive.google.com/file/d/17wTtAhhIa8kuBSn__B4iXWJm8NiZtovN/view?usp=sharing

**Comment by BlackburnUTG** [comment]
сделал текст векторным почти на всех страницах, кроме ~10стр которые баговались https://drive.google.com/file/d/1jeAF8y477EyYB8ECUEhM2i9AG4DxOHoQ/view?usp=sharing

**Comment by Phenomen** [comment]
Спасибо, взял на систему на перевод

**Comment by kmashkov** [comment]
> Спасибо, взял на систему на перевод

Супер, очень ждем!

**Comment by Hadgar** [comment]
Всем привет. Помогите новичку плз. Поставил Foundry, поставил русский перевод. Но ни один мир не запускается, пишет, что нужно обновление с версии 0.7.9 до версии 0.8.5, хотя у меня так и так стоит последняя бета 0.8.5. Или он наоборот говорит, что я могу играть только на версии 0.7.9? Но на нее не скачивается уже перевод. То есть пока что играть все равно придется на английском?
