### ISSUE TITLE
С новым обновлением частично слетел шрифт. И+ старая проблема в системе ведьмака.

### ISSUE THREAD

**Issue by DKtric3L** [phenomen/foundry-vtt-ru#41]
В основном, шрифт, который идёт с системой, остался, а где-то(Например в токенах) Шрифт дефолтный.
![изображение](https://user-images.githubusercontent.com/105752167/174460713-857149e0-07d9-45e0-a6d6-35eddab4c998.png)
Вторая проблема - в анкете без аддона скиллы персонажей имеют кроичневую плашку, но с включением аддона она пропадает, что не критично, но глаза режет.
![изображение](https://user-images.githubusercontent.com/105752167/174460744-5c40acf0-9b85-4142-8135-4f619c1a55db.png)
![изображение](https://user-images.githubusercontent.com/105752167/174460755-8b78a2e5-8dbd-483f-b9e6-c9517049c715.png)

**Comment by phenomen** [comment]
Исправил некоторые стили. Пока не буду закрывать тикет, если ещё что-то где-то криво, отпишись, т.к. я не знаком особо с системой.

**Comment by phenomen** [comment]
Другая проблема - довольно кривой и неполный перевод от некоего @DarkLeopard встроен в саму систему и я не могу его "переписать". Если нужно, напишите автору системы, чтобы он удалил встроенный перевод.

**Comment by DarkLeopard** [comment]
> Другая проблема - довольно кривой и неполный перевод от некоего @DarkLeopard встроен в саму систему и я не могу его "переписать". Если нужно, напишите автору системы, чтобы он удалил встроенный перевод.

"Встроен в систему" - это несколько раздельных файлов. Прежде чем кидаться словами, будет актуально разобраться в коде. Ничто не мешает сделать чистый форк и исправить под свои хотелки. 

Весь сделанный нами перевод основан на лицензионной книге правил Ведьмака с пропуском чересчур вольных трактовок, не встречающихся в книге. За подобную работу, коей пользуются бесплатно, нормальные люди говорят спасибо.

**Comment by phenomen** [comment]
> @DarkLeopard  "Встроен в систему" - это несколько раздельных файлов. Прежде чем кидаться словами, будет актуально разобраться в коде. Ничто не мешает сделать чистый форк и исправить под свои хотелки.

Это тебе следует "разбобраться в коде", тогда может ты бы увидел, что файл из системы грузится после файла перевода из модуля и любые мои правки просто не отображаются в игре из-за приоритета загрузки. В общем, ты оказал медвежью услугу своим неполноценным (70%) и неактуальным под последние обновления переводом.

**Comment by DarkLeopard** [comment]
> > @DarkLeopard  "Встроен в систему" - это несколько раздельных файлов. Прежде чем кидаться словами, будет актуально разобраться в коде. Ничто не мешает сделать чистый форк и исправить под свои хотелки.
> 
> Это тебе следует "разобраться в коде", тогда может ты бы увидел, что json из системы грузится после файла перевода из модуля и любые правки просто не отображаются из-за приоритета загрузки. В общем, ты оказал медвежью услугу своим неполноценным (70%) и неактуальным под последние обновления переводом.

Мы прекрасно играем всей компанией с русским переводом. 70% из головы взято? На тот момент отсутствовали 5-10 переводов, остальное было захардкожено в основном коде. Обнови перевод у разраба модуля, а не *есось чужие работы.

Перевод под json был встроен автором модуля и предполагал именно этот способ. Если есть проблемы с методом переводов - напиши автору мода или foundry, это не проблема людей, предоставляющих корректный (на тот момент) перевод фалов модуля.

**Comment by DKtric3L** [comment]
> Исправил некоторые стили. Пока не буду закрывать тикет, если ещё что-то где-то криво, отпишись, т.к. я не знаком особо с системой.

Спасибо за быстрый ответ и решение! Всё работает отлично. На токенах всё так же дефолт шрифт, но это не критично. Самое главное ты сумел решить. Ещё раз благодарю сердечно.
![изображение](https://user-images.githubusercontent.com/105752167/174502839-13d6dcd0-1f32-4ab3-b1ca-dc10abb143b3.png)
