### ISSUE TITLE
Не переводятся броски в чате, описания, названия и часть свойств в Staefinder

### ISSUE THREAD

**Issue by GuitarPyro** [phenomen/foundry-vtt-ru#55]
Установил всё по инструкции; описание предметов, звездолётов, заклинаний итд не переведно совсем, свойства перевелись частично, в чате все результаты бросков на английском. 
Пробовал переустанавливать модули (перевод, Babele и libWrapper), пересоздавал мир, нажимал вручную на листе персонажа кнопку "Перевод" (итог - все Not found), пробовал включать и отключать Babele.
Помимо этих модулей стоят всего три - Chat Portrait, Dice so nice и Simple dice roller, их включение-отключение эффекта не возымело.

![image](https://sun9-37.userapi.com/impg/ZYpNUH6BP0ZqnW6Zg4v3sT8Kx2FyQoqtwg2n5Q/yz5m5KGIPNU.jpg?size=715x728&quality=96&sign=3c6f907d30ee67b4a7ca8325efe80bcf&type=album) ![image](https://sun9-52.userapi.com/impg/-I50q8bArMXsdsgdWTIiR31N38TsE3BSBB8CbQ/2YzrcgRqNGw.jpg?size=292x839&quality=96&sign=936d0ec1083236fe676948e707249e1a&type=album)

Foundry -10 (билд 291)
Starfinder - 0.22.1
Babele - 2.4.0
Перевод 11.292.16
LibWrapper 1.12.12.0

**Comment by phenomen** [comment]
Переводом Starfinder никто не занимался очень давно и текущая версия устарела (переведено 76% строк).
Перевода библиотеки не было вообще.

**Comment by GuitarPyro** [comment]
Спасибо за ответ.
Очень жаль, что так.
