### ISSUE TITLE
Проблема с переводом TheWitcherTrpg

### ISSUE THREAD

**Issue by IHappyEndI** [phenomen/foundry-vtt-ru#67]
При установке последней версии модуля ломается перевод страницы инвентаря в системе ведьмака. Откат до прошлой версии перевода(в моем случае 11.307.6) помогает с данной проблемой. 
Пример как выглядит проблема:
![WitcherBug](https://github.com/phenomen/foundry-vtt-ru/assets/105805220/d9f34665-289d-4bd1-a1ad-afc4d73e336d)

Версия Foundry: v11.313
Версия модуля: v11.311
Версия системы: v0.97

**Comment by phenomen** [comment]
На примере не совсем понятно, что именно не так. Укажи конкретней.

**Comment by phenomen** [comment]
Убрал кастомные стили. Если у кого-то есть желание поработать над ними, можете создать PR.
