### ISSUE TITLE
Добавить возможность убрать "переключение рода прилагательных" из списка инструментов токенов

### ISSUE THREAD

**Issue by TrofimSelbs** [phenomen/foundry-vtt-ru#68]
Здравствуйте, модуль 10/10, имба, пушка сказка песня.
Пытался разобраться и немного разгрезти избыток инструментов на панели инструментов и набрёл на вот этот. Могли бы вы пожалуйста добавить возможность удалить вот этот инструмент из панели? Я его не использую совсем. Очень благодарен за всё 

![image](https://github.com/phenomen/foundry-vtt-ru/assets/124184162/32704e25-af50-406c-be10-3155cb31cca1)

**Comment by phenomen** [comment]
Fixed in d8b581d
