### ISSUE TITLE
Конфликт с модулем World of Darkness 5e

### ISSUE THREAD

**Issue by tleilaxian** [phenomen/foundry-vtt-ru#79]
Обновление модуля World of Darkness 5e (https://github.com/Rayji96/foundry-V5) имеет встроенный перевод на русский, который конфликтует с этим модулем. При включенном модуле перевода показывает почти всё в листе персонажа на английском. Можкт имеет смысл отключить перевод этой системы из модуля?

**Comment by phenomen** [comment]
Нет, это не имеет смысла. Автор модуля поменял структуру файла локализации, поэтому версия текущая не отображается корректно. Нужно обновить перевод в модуле.
